# Cross-build with an extracted MinGW toolchain and MSYS2 mingw64 SDK.
# Paths point to toolchain/usr and sdk/mingw64 respectively.
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)
foreach(name LANDESK_MINGW_ROOT LANDESK_WINDOWS_SDK)
  if(NOT DEFINED ENV{${name}})
    message(FATAL_ERROR "Set environment variable ${name} to an absolute path")
  endif()
endforeach()
set(_tools "$ENV{LANDESK_MINGW_ROOT}")
set(_sdk "$ENV{LANDESK_WINDOWS_SDK}")
set(CMAKE_C_COMPILER "${_tools}/bin/x86_64-w64-mingw32-gcc-posix")
set(CMAKE_CXX_COMPILER "${_tools}/bin/x86_64-w64-mingw32-g++-posix")
set(CMAKE_RC_COMPILER "${_tools}/bin/x86_64-w64-mingw32-windres")
set(CMAKE_FIND_ROOT_PATH "${_sdk}" "${_tools}/x86_64-w64-mingw32")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_PREFIX_PATH "${_sdk}")
set(OPENSSL_ROOT_DIR "${_sdk}")
set(PKG_CONFIG_EXECUTABLE "${CMAKE_CURRENT_LIST_DIR}/../scripts/windows-pkg-config.sh" CACHE FILEPATH "")
